let suggestions = [
    "Andaman and islands",
    "Andhra pradesh" ,
    "Arunachal pradesh",
    "Assam" ,
    "Bihar"	,
    "Chandigarh",
    "Chhattisgarh"	,
    "Dadra and nagar haveli",
    "Daman and diu",
    "Delhi"  ,
    "Goa"	,	
    "Gujarat"	,
    "Haryana",	 
    "Himachal Pradesh",
    "Jammu and kashmir",
    "Jharkhand"	,
    "Karnataka"	,
    "Kerala",	
    "Lakshdweep",
    "Madhya pradesh",
    "Maharashtra"	,
    "Manipur"	,
    "Meghalaya"	,
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punducherry"	,
    "Punjab",
    "Rajasthan"	,
    "Sikkim"	,
    "Tamil nadu" ,	
    "Telangana"	,
    "Tripura",
    "Uttar pradesh",
    "Uttarakhand",
    "West bengal"
];



